import Link from 'next/link'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Privacy Policy — Synapse',
}

export default function PrivacyPage() {
  return (
    <div
      style={{ backgroundColor: 'var(--bg)', color: 'var(--text-primary)' }}
      className="min-h-screen px-4 py-16"
    >
      <article className="mx-auto max-w-2xl space-y-10">

        {/* Header */}
        <div>
          <h1 className="text-3xl font-bold tracking-tight">Privacy Policy</h1>
          <p style={{ color: 'var(--text-secondary)' }} className="mt-2 text-sm">
            Last updated: 17 March 2025
          </p>
        </div>

        {/* 1. Introduction */}
        <section className="space-y-3">
          <h2 className="text-lg font-semibold">1. Introduction</h2>
          <p style={{ color: 'var(--text-secondary)' }} className="text-sm leading-relaxed">
            Synapse is a platform operated by <strong style={{ color: 'var(--text-primary)' }}>Bitlab</strong> for
            discovering and sharing AI assets — prompts, agents, apps, and workflows. This Privacy Policy explains
            what personal data we collect, why we collect it, how it is used, and your rights in relation to it.
          </p>
          <p style={{ color: 'var(--text-secondary)' }} className="text-sm leading-relaxed">
            By using Synapse you agree to the collection and use of information in accordance with this policy.
          </p>
        </section>

        {/* 2. Data We Collect */}
        <section className="space-y-3">
          <h2 className="text-lg font-semibold">2. Data We Collect</h2>
          <ul style={{ color: 'var(--text-secondary)' }} className="space-y-2 text-sm leading-relaxed">
            <li>
              <strong style={{ color: 'var(--text-primary)' }}>Account data</strong> — email address, username,
              and profile information you provide during registration.
            </li>
            <li>
              <strong style={{ color: 'var(--text-primary)' }}>Content data</strong> — assets, prompts, workflows,
              and comments you submit to the platform.
            </li>
            <li>
              <strong style={{ color: 'var(--text-primary)' }}>Usage data</strong> — view counts, stars, and
              activity logs generated by your interactions with the platform.
            </li>
            <li>
              <strong style={{ color: 'var(--text-primary)' }}>AI interaction data</strong> — prompts sent to AI
              features and token usage, retained in anonymised form for operational purposes.
            </li>
            <li>
              <strong style={{ color: 'var(--text-primary)' }}>Technical data</strong> — IP address (via
              Supabase/Vercel infrastructure) and browser type, collected automatically when you access the platform.
            </li>
          </ul>
        </section>

        {/* 3. Why We Collect It */}
        <section className="space-y-3">
          <h2 className="text-lg font-semibold">3. Why We Collect It</h2>
          <ul style={{ color: 'var(--text-secondary)' }} className="space-y-2 text-sm leading-relaxed list-disc list-inside">
            <li>Account management and authentication</li>
            <li>Platform functionality — search, contributions, and community features</li>
            <li>AI-powered features — refinement, tag suggestions, and the prompt assistant</li>
            <li>Security and abuse prevention</li>
            <li>Platform analytics and improvement</li>
          </ul>
        </section>

        {/* 4. Third-Party Services */}
        <section className="space-y-3">
          <h2 className="text-lg font-semibold">4. Third-Party Services</h2>
          <p style={{ color: 'var(--text-secondary)' }} className="text-sm leading-relaxed">
            We share data with the following third-party services to operate the platform:
          </p>
          <ul style={{ color: 'var(--text-secondary)' }} className="space-y-2 text-sm leading-relaxed">
            <li>
              <strong style={{ color: 'var(--text-primary)' }}>Supabase</strong> — database and authentication
              hosting. EU data processing is available.
            </li>
            <li>
              <strong style={{ color: 'var(--text-primary)' }}>Vercel</strong> — application hosting and
              deployment.
            </li>
            <li>
              <strong style={{ color: 'var(--text-primary)' }}>Google / Gemini API</strong> — AI features.
              Prompts and content may be processed by Google&apos;s infrastructure.
            </li>
            <li>
              <strong style={{ color: 'var(--text-primary)' }}>Resend</strong> — transactional email delivery.
            </li>
            <li>
              <strong style={{ color: 'var(--text-primary)' }}>Google OAuth</strong> — if you choose to sign in
              with your Google account.
            </li>
          </ul>
        </section>

        {/* 5. Data Retention */}
        <section className="space-y-3">
          <h2 className="text-lg font-semibold">5. Data Retention</h2>
          <ul style={{ color: 'var(--text-secondary)' }} className="space-y-2 text-sm leading-relaxed list-disc list-inside">
            <li>Account data is retained for as long as your account is active.</li>
            <li>All personal data is deleted upon a valid account deletion request.</li>
            <li>AI usage logs are retained for 90 days for operational purposes, then deleted.</li>
          </ul>
        </section>

        {/* 6. Your Rights (GDPR) */}
        <section className="space-y-3">
          <h2 className="text-lg font-semibold">6. Your Rights (GDPR)</h2>
          <p style={{ color: 'var(--text-secondary)' }} className="text-sm leading-relaxed">
            If you are located in the European Economic Area, you have the following rights regarding your personal data:
          </p>
          <ul style={{ color: 'var(--text-secondary)' }} className="space-y-2 text-sm leading-relaxed list-disc list-inside">
            <li>Right to access your data</li>
            <li>Right to correction of inaccurate data</li>
            <li>Right to deletion (see Account Deletion below)</li>
            <li>Right to data portability</li>
            <li>Right to object to processing</li>
          </ul>
          <p style={{ color: 'var(--text-secondary)' }} className="text-sm leading-relaxed">
            To exercise any of these rights, contact us at{' '}
            <a href="mailto:hello@bitlab.pt" style={{ color: 'var(--accent)' }} className="hover:underline">
              hello@bitlab.pt
            </a>.
          </p>
        </section>

        {/* 7. Cookies */}
        <section className="space-y-3">
          <h2 className="text-lg font-semibold">7. Cookies</h2>
          <ul style={{ color: 'var(--text-secondary)' }} className="space-y-2 text-sm leading-relaxed">
            <li>
              <strong style={{ color: 'var(--text-primary)' }}>Strictly necessary</strong> — Supabase session
              cookies are used for authentication and do not require consent.
            </li>
            <li>
              <strong style={{ color: 'var(--text-primary)' }}>Cookie consent</strong> — We use Iubenda to manage
              and record your cookie consent preferences.
            </li>
          </ul>
        </section>

        {/* 8. Account Deletion */}
        <section className="space-y-3">
          <h2 className="text-lg font-semibold">8. Account Deletion</h2>
          <p style={{ color: 'var(--text-secondary)' }} className="text-sm leading-relaxed">
            You can delete your account at any time from your{' '}
            <Link href="/profile" style={{ color: 'var(--accent)' }} className="hover:underline">
              Profile Settings
            </Link>
            . On deletion:
          </p>
          <ul style={{ color: 'var(--text-secondary)' }} className="space-y-2 text-sm leading-relaxed list-disc list-inside">
            <li>All personal data is permanently deleted within 30 days.</li>
            <li>
              Public assets you submitted may be anonymised rather than deleted, to preserve community content
              integrity. Your name will be removed from all such assets.
            </li>
          </ul>
        </section>

        {/* 9. Contact */}
        <section className="space-y-3">
          <h2 className="text-lg font-semibold">9. Contact</h2>
          <ul style={{ color: 'var(--text-secondary)' }} className="space-y-1 text-sm">
            <li>
              <strong style={{ color: 'var(--text-primary)' }}>Data controller:</strong> Bitlab
            </li>
            <li>
              <strong style={{ color: 'var(--text-primary)' }}>Email:</strong>{' '}
              <a href="mailto:hello@bitlab.pt" style={{ color: 'var(--accent)' }} className="hover:underline">
                hello@bitlab.pt
              </a>
            </li>
            <li>
              <strong style={{ color: 'var(--text-primary)' }}>Website:</strong>{' '}
              <span>synapse.bitlab.pt</span>
            </li>
          </ul>
        </section>

        {/* 10. Changes to This Policy */}
        <section className="space-y-3">
          <h2 className="text-lg font-semibold">10. Changes to This Policy</h2>
          <p style={{ color: 'var(--text-secondary)' }} className="text-sm leading-relaxed">
            We will notify users of material changes to this policy via email. Continued use of the platform after
            changes are posted constitutes your acceptance of the updated policy.
          </p>
        </section>

        {/* Footer nav */}
        <div
          className="border-t pt-6 text-sm"
          style={{ borderColor: 'var(--bg-border)', color: 'var(--text-secondary)' }}
        >
          <Link href="/terms" style={{ color: 'var(--accent)' }} className="hover:underline">
            Terms of Service →
          </Link>
        </div>

      </article>
    </div>
  )
}
